### ISSUE TITLE
Weird snapshot resolution

### ISSUE THREAD

**Issue by lauterry** [percy/percy-nightwatch#4]
Hi

I have made a snapshot of our login page. [Here is the link to the snapshot](https://percy.io/Perfectstay/La-Collection-Air-France/builds/1212450)

I have a resolution problem in the snapshot in percy.io since the expected resolution is as shown in the following screenshot (1366 x768) :  

![capture d ecran 2018-12-02 a 11 28 36](https://user-images.githubusercontent.com/1374238/49338698-6d227e00-f625-11e8-9737-acff6d227622.jpg)

Here is the code : 

```
browser.resizeWindow(1366, 768);
// .... some nightwatch assertions
browser.percySnapshot("home | login | desktop", { widths: [1366] });
```

I can't see where the problem is. There is no issue about resolution with my other snapshots.

Best regards

**Comment by lauterry** [comment]
Hi

Any update on this issue ?

**Comment by djones** [comment]
Hi @lauterry,

I can understand what you're hoping to achieve but Percy doesn't match the viewport height you happen to have set in your test framework. This is why you're seeing a different height in Percy compared to what you have told Nightwatch to use there.

We do support setting the viewport width though, which I see you are using 👍 

Thanks,
David.
